from django.urls import path, include
from . import views

urlpatterns = [
    path('detail/<str:mode>/<str:pk>/', views.InterviewsUpdate.as_view()),
    #path('<str:pk>/', views.InterviewsUpdate.as_view()),
    path('create/<str:msg>/', views.InterviewsCreate.as_view()),
    #path('', views.InterviewsList.as_view()),
    path('', views.start_interviews),
    path('record/', views.record),
    path('list/<str:msg>/', views.clientlist),
#    path('update/<str:pk>/', views.InterviewsUpdate.as_view()),
    path('summary/<str:pk>/', views.summary_ready),
    path('summary/<str:pk>/<str:stype>/', views.summary),
    path('sentimental/<str:pk>/', views.sentimental),
    path('wordcloud/<str:pk>/', views.wordcloud),
    path('document/<str:pk>/', views.document),
    path('search/<str:q>/', views.InterviewsSearch.as_view()),
    path('delete/<str:interview_pk>/', views.delete, name='interview_delete'),
    path('verbatim/<str:doc_type>/<str:pk>/<str:quiet_basis>', views.verbatim),
    path('report/<str:pk>/<str:label>', views.report),
    path('client/<str:pk>/', views.client_page, name='client_page'),
    path('client/delete/<str:pk>/', views.client_delete, name='client_delete'),
    path('client/modify/<str:pk>/', views.client_modify, name='client_modify'),
    path('client/pwcheck/<str:pk>/', views.client_pwcheck, name='client_pwcheck'),
    path('add/client/<str:redir>/', views.ClientCreate.as_view()),
    path('regist/code/', views.code_regist, name='code_regist'),
    path('generate/code/', views.code_generate, name='code_generate'),
    path('dbupdate/<str:msg>/', views.dbupdate),
    path('sentenceupdate/<str:pk>/', views.sentenceUpdate),
    path('addspeaker/<str:pk>/', views.addspeaker),
    path('inaction/', views.inaction),
    path('purchase/', views.PurchaseCreate.as_view()),
    path('purchase/manage/', views.PurchaseManageList.as_view()),
    path('purchase/regist/<str:msg>/', views.purchase_regist),
    path('purchase/request/', views.purchase_request),
    path('purchase/ownlist/', views.purchase_ownlist),
    path('purchase/codeApprove/', views.purchase_codeApprove),
    path('purchase/paysuccess/', views.pay_success),
    path('realtime/',views.RealtimeInterviews)
    #path('purchase/paycancel/', views.pay_cancel)
#    path('purchase/payfail/', views.payfail),
 #   path('create/', views.InterviewsCreate.as_view()),
 #   path('update/<int:pk>/', views.InterviewsUpdate.as_view()),
 #   path('search/<str:q>/', views.InterviewsSearch.as_view()),
 #   path('', views.PostList.as_view()),
]